http://localhost:3000/trimmers

### add trimmer
POST http://localhost:3000/smartTV
Content-Type: application/json

 {
      "title": "ONEPLUS 108 cm (43 inch) Full HD Smart LED TV, 43Y1",
      "image": "https://www.reliancedigital.in/medias/ONEPLUS-43Y1-TV-491895011-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3wyNTQ5NHxpbWFnZS9qcGVnfGltYWdlcy9oOGQvaDZmLzk4MTAwNTg1NzU5MDIuanBnfDRlNjk2MTc0MjNiODNmYmZkNmVjNWQwMjM1N2QxMzExOWFkNzcyOTNiY2M3ODU0ZmUyN2Y5OWEyNjExNzFkYTY",
      "brand": "Oneplus",
      "dealprice": "₹22,999.00",
      "offerprice": "₹29,999.00",
      "discount": "23%(₹7,000)",
      "tag": "LIMITED TIME OFFER ",
      "description": "Washable Head, LED battery indicator"
    }
    

